### ISSUE TITLE
Bottom Nav persist when user logout of the app

### ISSUE THREAD

**Issue by raymondDangdat** [lakshydeep-14/30FlutterTips#3]
In my app there's a logout button, when the user logout, the bottom nav still persist. 
How do I handle that?

**Comment by lakshydeep-14** [comment]
Please use this:

` Navigator.of(context, rootNavigator: true).pushAndRemoveUntil(
                            MaterialPageRoute(
                              builder: (BuildContext context) {
                                return const UserLogin();
                              },
                            ),
                            (_) => false,
                          );`
